# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79c03fba1a612e1fd9617f0d7cc77900d68a88744c2e5bf197fb78f2ec2d4a3ecdba2c388b1744b3c17cbb026d99a77a5d5868a52f29499e6183fcfc3d7beac4

test:
  secret_key_base: d65d613dba3c691733e8b591ec7b99e0052afbfa5769d542d58166ef41f5d9e9827d33fee75f4beee37aad8b3462c584bd261324a5a6f72db815f84380a868f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
